// atlasManifest — maps a source PNG (as used in <img src>) to its pose atlas.
//
// assets/anim/manifest.json is generated by "Blender designs/icons3d/pack_atlas.py"
// and keyed by repo-relative source paths, e.g.
//   "assets/avatars_v2/common/doctor.png" → { atlas, cell, cols, count, kind, frames, axes }
// <img> srcs arrive in many shapes (URI-encoded Hebrew, absolute URLs, "./"
// prefixes), so lookups normalize first.

export const MANIFEST_URL = 'assets/anim/manifest.json';

export function normalizeAssetPath(src) {
  if (!src) return null;
  let s = String(src);
  const i = s.indexOf('assets/');
  if (i < 0) return null;
  s = s.slice(i).split(/[?#]/)[0];
  try { s = decodeURI(s); } catch { /* keep as-is */ }
  return s;
}

export function createAtlasManifest({ fetchFn = globalThis.fetch?.bind(globalThis), url = MANIFEST_URL } = {}) {
  let loading = null;
  let atlases = null;

  function load() {
    if (!loading) {
      loading = (typeof fetchFn === 'function'
        ? fetchFn(url).then(r => (r.ok ? r.json() : null))
        : Promise.resolve(null))
        .then(json => { atlases = json?.atlases ?? {}; return atlases; })
        .catch(() => { atlases = {}; return atlases; });
    }
    return loading;
  }

  // Sync lookup once loaded (null before load or when there is no atlas).
  function lookup(src) {
    const key = normalizeAssetPath(src);
    return (key && atlases?.[key]) || null;
  }

  async function atlasFor(src) {
    await load();
    return lookup(src);
  }

  return { load, lookup, atlasFor };
}

let _singleton = null;
export function getAtlasManifest() {
  if (!_singleton) _singleton = createAtlasManifest();
  return _singleton;
}

export function _resetAtlasManifestForTests() { _singleton = null; }
